os: osx
language: csharp
before_install:
      - command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable; fi
install:
- nuget restore ./GLTFSerialization/GLTFSerialization.sln
- sudo python2 ./scripts/install-unity.py --package Unity 2017.1.1f1
before_script:
- sudo chmod -R a+rwx /Applications/Unity
script:
- msbuild ./GLTFSerialization/GLTFSerialization.sln
- "./scripts/export-unity-package.sh"
deploy:
  provider: releases
  api_key:
    secure: VtkGC+8OGR99sxDg6Gth2l23u/XWi62a8nBCSZ/++hvRaELX3ntKs/g4SyMLEdYyBdxkZpzDwG2rWJo6x1UWRYHQjoStZ9I1+6x+02oPLZajvOKGc777arFPI+2bRe/ISc7ZN3MY2iw0rbOUYnsnFMMh22mmYxBH8E9sg9SxmhxtsJlbrBcaIr7BP7OSb38G4V/+9h+ZPrYGjob4sa+iELcJYvjdNCYMwpr0R0U1RHBb5HYDnCm17bdPDoOxBXKGIA6czV6YQ9gPGGIBSMSxvCb+eprxYPOJnGg1xGQiMmZwbTpLaK04pNAWwKxg3qQwm4AjoepNCd/tq9C74hQefxEzueQwL4Su5IQ4hl/10Yu1F6OQiYtDRWwPv8FNdHmHg7C9bomTAnUrFE/Pz+rLLIFFcx8EVzg+nu0mBH1wutlXpAd+WJ37oCUe27HOpyej6ltQcE8iOE8dkvrtDaO+k7uDUGsZhQzH2lbjfVmPqATPp9JXmE6nKTP9x/MvyDJT1L2O/32HqVdN2H9mH8B3/O0vfPjJAzznp/GzYRNmj78YUuWEg93TIWEWvX4T5mqVJQeZVlliwUoJBV8NvdCV9UEdtuXE8V1hwnScXBPoh3ELpmoXDdGxYXXgz/C/uj5LGSkBHKG6IEH6BMLdjJUgkWoaDuB11UVWCQM54643ma8=
  file: ./current-package/UnityGLTF.unitypackage
  skip_cleanup: true
  on:
    repo: KhronosGroup/UnityGLTF
    tags: true
